# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['UI\\update.py'],
    pathex=[],
    binaries=[],
    datas=[('UI\\assets\\logo.ico', 'assets')],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter', '_tkinter',
        'test', 'unittest',
        'email', 'xml', 'xmlrpc',
        'pydoc', 'pydoc_data',
        'doctest', 'difflib',
        'lib2to3', 'ensurepip', 'venv',
        'idlelib', 'turtledemo', 'turtle',
        'curses',
        'scipy', 'numpy', 'sklearn',
        'matplotlib', 'pandas',
        'PIL', 'Pillow',
        'pyautogui', 'keyboard', 'pystray',
        'pyshark', 'pygetwindow',
        'flask', 'webview',
        'multiprocessing.popen_spawn_posix',
        'multiprocessing.popen_fork',
        'multiprocessing.popen_forkserver',
    ],
    noarchive=False,
    optimize=2,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='update',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['UI\\assets\\logo.ico'],
)
