# This workflow builds DnDTools using build_app.bat and uploads it to a GitHub Release manually
name: Build and Release DnDTools

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (example: v1.0.0)'
        required: true
        default: 'v2.0.0'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: UI/requirements.txt

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r UI/requirements.txt
          pip install pyinstaller

      - name: Run build script (build_app.bat)
        shell: cmd
        run: |
          build_app.bat

      - name: Compress EXE with UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          version: latest
          files: |
            dist/*.exe
          args: --best

      - name: Create GitHub Pre-Release and Upload executable
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: Test-Release ${{ github.event.inputs.tag }}
          files: dist/DnDTools.exe
          fail_on_unmatched_files: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
